import Head from "next/head";
import { Posts, User } from "@/types";
import { Box, Stack } from "@mui/material";
import { PostComponent } from "@/components/Features/PostComponent";
import { PostListSkeleton } from "@/components/Skeleton";
import { useAxiosGet } from "@/hooks/AxiosHooks";
import { useUserQuery } from "@/hooks/UserQueries";
import { usePostQuery } from "@/hooks/PostQueries";

export default function Home() {

  // const { data: posts, isLoading } = useAxiosGet<Posts[]>(['posts'], 'https://jsonplaceholder.typicode.com/posts')
  // const { data: users } = useAxiosGet<User[]>(['users'], 'https://jsonplaceholder.typicode.com/users')


  const { data: posts, isLoading } = usePostQuery<Posts[]>();
  const { data: users, error } = useUserQuery<User[]>();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Stack maxWidth={300} mx={'auto'} spacing={2}>
            {isLoading && <PostListSkeleton />}
            {
              users && posts?.map((p) => {
                let user = users?.find((u) => u.id === p.userId)
                return <PostComponent key={p.id} post={p} user={user} />
              })
            }
          </Stack>
        </Box>
      </main>
    </>
  );
}