import Head from "next/head";
import axios from "axios";
import { useQuery } from "@tanstack/react-query";
import { Posts, User } from "@/types";
import { Avatar, Box, Card, CardContent, CardHeader, Stack, Typography } from "@mui/material";
import Link from "next/link";

export default function Home() {
  const { data: posts, isLoading, error } = useQuery<Posts[]>({
    queryKey: ['posts'],
    queryFn: () => axios.get('https://jsonplaceholder.typicode.com/posts').then((res) => res.data),
  })

  const { data: users, isLoading: userLoading, error: userError } = useQuery<User[]>({
    queryKey: ['users'],
    queryFn: () => axios.get('https://jsonplaceholder.typicode.com/users').then((res) => res.data),
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box >
          <Stack maxWidth={300} mx={'auto'} spacing={2}>
            {
              users && posts?.map((p) => {
                let user = users?.find((u) => u.id === p.userId)
                return <PostComponent key={p.id} post={p} user={user} />
              })
            }
          </Stack>
        </Box>
      </main>
    </>
  );
}


export const PostComponent = ({ post, user }: { post: Posts, user?: User }) => {
  return (
    <Card variant="elevation">
      {user && <Link href={`/user/${user.id}`}>
        <CardHeader
          avatar={
            <Avatar alt={user?.name}>{user?.name[0]}</Avatar>
          }
          title={user.name}
        />
      </Link>}
      <CardContent>
        <Link href={`/post/${post.id}`}>
          <Typography variant="body1" color="text.secondary">
            {post.title}
          </Typography>
        </Link>
      </CardContent>
    </Card>
  )
}