import Head from "next/head";
import axios from "axios";
import { useQuery } from "@tanstack/react-query";
import { Posts, User } from "@/types";
import { Box, Stack } from "@mui/material";
import { PostComponent } from "@/components/Features/PostComponent";
import { PostListSkeleton } from "@/components/Skeleton";

export default function Home() {
  const { data: posts, isLoading, error } = useQuery<Posts[]>({
    queryKey: ['posts'],
    queryFn: () => axios.get('https://jsonplaceholder.typicode.com/posts').then((res) => res.data),
  })

  const { data: users, isLoading: userLoading, error: userError } = useQuery<User[]>({
    queryKey: ['users'],
    queryFn: () => axios.get('https://jsonplaceholder.typicode.com/users').then((res) => res.data),
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Stack maxWidth={300} mx={'auto'} spacing={2}>
            {isLoading && <PostListSkeleton />}
            {
              users && posts?.map((p) => {
                let user = users?.find((u) => u.id === p.userId)
                return <PostComponent key={p.id} post={p} user={user} />
              })
            }
          </Stack>
        </Box>
      </main>
    </>
  );
}